fault point=-92027613
event=CRASH
pos=BEFORE
nodeIp=172.42.0.2
ioID=1373891192
ioCallStack=[org.apache.hadoop.ha.protocolPB.HAServiceProtocolServerSideTranslatorPB.getServiceStatus(HAServiceProtocolServerSideTranslatorPB.java:177), org.apache.hadoop.ha.proto.HAServiceProtocolProtos$HAServiceProtocolService$2.callBlockingMethod(HAServiceProtocolProtos.java:6224), org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:600), org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:568), org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:552), org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093), org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1035), org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:963), java.security.AccessController.doPrivileged(Native Method), javax.security.auth.Subject.doAs(Subject.java:422), org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878), org.apache.hadoop.ipc.Server$Handler.run(Server.java:2966)]
path=FAVMSG:FAVMSG:172.42.0.2&170#113
ioAppearIdx=27
end
